### ISSUE TITLE
lstlisting numbering problem

### ISSUE THREAD

**Issue by furihr** [persian-tex/xepersian#2]
XePersian had some problems with `lstlisting` numbering, which were fixed in June. I have just discovered there still remains one issue unsolved. The numbering in the caption and `lstlistoflistings` is RTL but in the references (`\ref{key}`) it's LTR.

**Comment by furihr** [comment]
The MWE

    \documentclass[12pt,a4paper]{report}


    \usepackage[usenames,dvipsnames]{color}
    \usepackage{listings}
    \usepackage{xepersian}
    \settextfont{Nazli}

    \definecolor{customblue}{RGB}{235,241,245}
    \lstdefinestyle{C++Style}{%
      backgroundcolor=\color{customblue},
      breaklines=true,
      basicstyle=\footnotesize\ttfamily,
      keywordstyle=\color{blue},
      commentstyle=\color{OliveGreen}\textit,
      stringstyle=\color{red},
      numbers=left,
      numberstyle={\tiny\lr},
    %   stepnumber=5,
      showspaces = false,
      showstringspaces = false,
      tabsize = 2,
      frame=single,
      xleftmargin=5pt,
      xrightmargin=3pt,
      language =  C++,
      aboveskip = 20pt,
      rulecolor=\color{black},
    %   captionpos=b,
    %   title={\stepcounter{lstlisting}\rl{\lstlistingname{} \thelstlisting:\quad\lstname}},
      captiondirection=RTL,
    }


    \lstnewenvironment{C++Code}[1][]
    {
      \lstset{style=C++Style, #1}
    }{}

    \begin{document}
    \lstlistoflistings
    \chapter{فصل اول}
    \chapter{فصل دوم}

    برنامه‌ی \ref{hello-world}

    \begin{LTR}
    \begin{C++Code}[caption={\label{hello-world} 
    \lr{Hello, World!}}]
    #include<iostream>
    int main(){
      std::cout << "Hello, World!" << std::endl;
      return 0;
    }
    \end{C++Code}
    \end{LTR}

    \end{document}

**Comment by persian-tex** [comment]
I fixed this one in the `bidi` package (I will upload the new version to CTAN tonight).
