### ISSUE TITLE
Numbering figures

### ISSUE THREAD

**Issue by furihr** [persian-tex/xepersian#3]
Everything in a `xepersian` document is numbered RTL, except the `figure`s. Furthermore, the separator  for everything else is a dot (.), but for `figure`s it's a dash (-).

**Comment by vafa** [comment]
Hello furihr

Thanks for your bug reports. You have made three bug reports but non of them contains a minimal working example that shows the problem. Please add a minimal working example to each of the issues so that I can track the problem and fix it.

Your sincerely,
  Vafa

**Comment by furihr** [comment]
Hello Vafa,

I added the MWE for the other two bugs. This one you can close. It was a mistake.

Thanks,
Furihr
