### ISSUE TITLE
Text and cell orientation in `longtable` environment

### ISSUE THREAD

**Issue by furihr** [persian-tex/xepersian#4]
`longtable`s don't work with `xepersian`/`bidi`. The orientation of the cells and the text within the cells are wrong.

Example:

    \documentclass[12pt,a4paper]{report}

    \usepackage{longtable}
    \usepackage{xepersian}
    \settextfont{Nazli}
    \begin{document}
    \chapter{فصل اول}
    \chapter{فصل دوم}

    \begin{longtable}{|c|c|c|}
    \caption{جدول بلند}\\
    \hline
     اولین سلول & دومین سلول & سومین سلول\\
    \hline
    \end{longtable}
    \end{document}

**Comment by vafa** [comment]
Use the experimental `bidi-longtable` package.
