### ISSUE TITLE
Colored Links

### ISSUE THREAD

**Issue by mebrahimian1990** [persian-tex/xepersian#5]
Hi, I'm using `xepersian` with `hyperref` including its color options. When I use the `\nameref` command, if the link breaks in a line, the color of whole two lines including the link will change. I set the `breaklink` option of `hyperref` to false but the problem still occurs. The same issue exists when one cites to a long name reference using `natbib` package, but there I solved it temporary using `nonamebreak` option of `natbib` package. What's the problem?
````latex
\documentclass[a4paper]{book}
\usepackage{hyperref}
\hypersetup{colorlinks,breaklinks=false}
\usepackage{xepersian}
\settextfont[Scale=1]{XBNiloofar}

\begin{document}
\chapter{فصل اول که برای توضیح مشکل آورده شده است.}
\label{chap1}

\chapter{فصل دوم}
همانطور که مشاهده می‌کنید هر دوی این خط با آدرس دادن به \nameref{chap1} رنگی می‌شوند.

ولی اگر در یک خط باشد، آدرس به \nameref{chap1} مشکلی ندارد.
\end{document}
````

**Comment by vafa** [comment]
This is an engine bug and will be fixed with the new `xetex` binary available in TeXLive 2015.

**Comment by mebrahimian1990** [comment]
Hi,
I update my distribution to texlive 2015 but the problem is not solved
Thanks

**Comment by vafa** [comment]
Please see [this question and answer](http://qa.parsilatex.com/5531).
